name: mirror_scorpion  
description: "ميرور سكربيون - حيث تُصنع البدايات"  
publish_to: 'none'  
version: 1.0.0+1  
  
environment:  
  sdk: '>=3.0.0 <4.0.0'  
  
dependencies:  
  flutter:  
    sdk: flutter  
  flutter_localizations:  
    sdk: flutter  
  cupertino_icons: ^1.0.6  
  provider: ^6.1.1  
  shared_preferences: ^2.2.0  
  intl: ^0.19.0  
  flutter_tts: ^3.8.5  
  speech_to_text: ^6.6.0  
  http: ^1.1.0  
  path_provider: ^2.1.1  
  share_plus: ^7.2.1  
  device_info_plus: ^9.1.0  
  google_mlkit_text_recognition: ^0.11.0  
  google_mlkit_translation: ^0.8.0  
  dash_bubble: ^0.0.6  
  
dev_dependencies:  
  flutter_test:  
    sdk: flutter  
  flutter_lints: ^3.0.0  
  
flutter:  
  uses-material-design: true  
  assets:  
    - assets/images/  
